import {
  DatabaseSchema,
  VocabItemsTable,
  PhraseologicalUnitsTable,
  VocabContextExamplesTable,
  PhoneticRulesTable,
  GrammarRulesTable,
  ErrorTaxonomyTable,
} from '../../core/types/database';
import { Kysely, Insertable } from 'kysely';

export interface SeedDataset {
  vocabItems: Insertable<VocabItemsTable>[];
  phraseUnits: Insertable<PhraseologicalUnitsTable>[];
  contextExamples: Insertable<VocabContextExamplesTable>[];
  phoneticRules: Insertable<PhoneticRulesTable>[];
  grammarRules: Insertable<GrammarRulesTable>[];
  errorTaxonomy: Insertable<ErrorTaxonomyTable>[];
}

export const SEED_DATA: SeedDataset = {
  vocabItems: [
    // A1 - A2 (High-Frequency Fundamentals & Function Words)
    {
      id: 'voc_a1_01',
      word: 'always',
      grammatical_dimension: 'FUNCTION',
      part_of_speech: 'ADVERB',
      subcategory: 'Frequency Adverb',
      definition_en: 'At all times; on every occasion.',
      translation_es: 'Siempre',
      ipa_general_american: 'ˈɔːlweɪz',
      ipa_received_pronunciation: 'ˈɔːlweɪz',
      cefr_level: 'A1',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify([]),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_a1_02',
      word: 'because',
      grammatical_dimension: 'FUNCTION',
      part_of_speech: 'CONJUNCTION',
      subcategory: 'Subordinating Conjunction',
      definition_en: 'For the reason that; since.',
      translation_es: 'Porque / Debido a que',
      ipa_general_american: 'bɪˈkəz',
      ipa_received_pronunciation: 'bɪˈkɒz',
      cefr_level: 'A1',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['cause']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_a1_03',
      word: 'between',
      grammatical_dimension: 'FUNCTION',
      part_of_speech: 'PREPOSITION',
      subcategory: 'Spatial Preposition',
      definition_en: 'In or through the space separating two objects or points.',
      translation_es: 'Entre (dos personas o cosas)',
      ipa_general_american: 'bɪˈtwin',
      ipa_received_pronunciation: 'bɪˈtwiːn',
      cefr_level: 'A1',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify([]),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_a1_04',
      word: 'library',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'NOUN',
      subcategory: 'Place',
      definition_en: 'A building or room containing collections of books and periodicals for reading or borrowing.',
      translation_es: 'Biblioteca',
      ipa_general_american: 'ˈlaɪbrɛri',
      ipa_received_pronunciation: 'ˈlaɪbrəri',
      cefr_level: 'A2',
      is_false_friend: 1,
      false_friend_note: 'No confundir con "librería" (tienda de libros = bookstore / bookshop).',
      morphological_family_json: JSON.stringify(['librarian']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_a2_01',
      word: 'actually',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADVERB',
      subcategory: 'Discourse Marker',
      definition_en: 'In fact; really; as a matter of fact.',
      translation_es: 'En realidad / Realmente / De hecho',
      ipa_general_american: 'ˈæktʃuəli',
      ipa_received_pronunciation: 'ˈæktʃuəli',
      cefr_level: 'A2',
      is_false_friend: 1,
      false_friend_note: 'No significa "actualmente" (eso es "currently" o "nowadays").',
      morphological_family_json: JSON.stringify(['actual', 'actuality']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_a2_02',
      word: 'currently',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADVERB',
      subcategory: 'Time Adverb',
      definition_en: 'At the present time; now.',
      translation_es: 'Actualmente / En este momento',
      ipa_general_american: 'ˈkɜːrəntli',
      ipa_received_pronunciation: 'ˈkʌrəntli',
      cefr_level: 'A2',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['current']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_a2_03',
      word: 'attend',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'VERB',
      subcategory: 'Action Verb',
      definition_en: 'Be present at an event, meeting, or function.',
      translation_es: 'Asistir / Ir a (un evento o clase)',
      ipa_general_american: 'əˈtɛnd',
      ipa_received_pronunciation: 'əˈtɛnd',
      cefr_level: 'A2',
      is_false_friend: 1,
      false_friend_note: 'No significa "atender" a un cliente (eso es "to serve" o "to assist").',
      morphological_family_json: JSON.stringify(['attendance', 'attendant']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_a2_04',
      word: 'assist',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'VERB',
      subcategory: 'Action Verb',
      definition_en: 'Help someone, typically by doing a share of the work.',
      translation_es: 'Ayudar / Auxiliar',
      ipa_general_american: 'əˈsɪst',
      ipa_received_pronunciation: 'əˈsɪst',
      cefr_level: 'A2',
      is_false_friend: 1,
      false_friend_note: 'No significa "asistir a un evento" (eso es "to attend").',
      morphological_family_json: JSON.stringify(['assistant', 'assistance']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_a2_05',
      word: 'notice',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'VERB',
      subcategory: 'Perception Verb',
      definition_en: 'Become aware of or pay attention to something.',
      translation_es: 'Notar / Darse cuenta de',
      ipa_general_american: 'ˈnoʊtɪs',
      ipa_received_pronunciation: 'ˈnəʊtɪs',
      cefr_level: 'A2',
      is_false_friend: 1,
      false_friend_note: 'Como sustantivo significa "aviso/notificación", no "noticia" (noticia es "news").',
      morphological_family_json: JSON.stringify(['noticeable', 'unnoticed']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_a2_06',
      word: 'realize',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'VERB',
      subcategory: 'Cognitive Verb',
      definition_en: 'Become fully aware of something as a fact; understand clearly.',
      translation_es: 'Darse cuenta de / Comprender',
      ipa_general_american: 'ˈriːəˌlaɪz',
      ipa_received_pronunciation: 'ˈrɪəlaɪz',
      cefr_level: 'A2',
      is_false_friend: 1,
      false_friend_note: 'Casi nunca significa "realizar" una tarea (eso es "to carry out", "to make", o "to perform").',
      morphological_family_json: JSON.stringify(['realization']),
      created_at: '2026-09-29T10:00:00Z',
    },

    // B1 (Intermediate Functional Core, Dependent Prepositions & False Friends)
    {
      id: 'voc_b1_01',
      word: 'depend',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'VERB',
      subcategory: 'Dependent Preposition Verb',
      definition_en: 'Be controlled or determined by.',
      translation_es: 'Depender (siempre seguido de "on")',
      ipa_general_american: 'dɪˈpɛnd',
      ipa_received_pronunciation: 'dɪˈpɛnd',
      cefr_level: 'B1',
      is_false_friend: 0,
      false_friend_note: 'Error común en hispanohablantes: decir *"depend of" en lugar de "depend on".',
      morphological_family_json: JSON.stringify(['dependence', 'dependent', 'independent', 'dependable']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b1_02',
      word: 'rely',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'VERB',
      subcategory: 'Dependent Preposition Verb',
      definition_en: 'Trust or depend on with full confidence.',
      translation_es: 'Confiar en / Depender de (seguido de "on")',
      ipa_general_american: 'rɪˈlaɪ',
      ipa_received_pronunciation: 'rɪˈlaɪ',
      cefr_level: 'B1',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['reliable', 'reliance', 'unreliable']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b1_03',
      word: 'sensible',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Descriptive Adjective',
      definition_en: 'Chosen in accordance with wisdom or prudence; practical and reasonable.',
      translation_es: 'Sensato / Prudente / Juicioso',
      ipa_general_american: 'ˈsɛnsəbəl',
      ipa_received_pronunciation: 'ˈsɛnsɪbl',
      cefr_level: 'B1',
      is_false_friend: 1,
      false_friend_note: 'No significa "sensible" (eso es "sensitive").',
      morphological_family_json: JSON.stringify(['sense', 'sensibly']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b1_04',
      word: 'sensitive',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Descriptive Adjective',
      definition_en: 'Quick to detect or respond to slight changes or emotional stimuli.',
      translation_es: 'Sensible / Delicado / Susceptible',
      ipa_general_american: 'ˈsɛnsətɪv',
      ipa_received_pronunciation: 'ˈsɛnsɪtɪv',
      cefr_level: 'B1',
      is_false_friend: 1,
      false_friend_note: 'No significa "sensato" (eso es "sensible").',
      morphological_family_json: JSON.stringify(['sensitivity', 'sensitize']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b1_05',
      word: 'embarrassed',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Emotional State',
      definition_en: 'Feeling awkward, self-conscious, or ashamed.',
      translation_es: 'Avergonzado / Apenado',
      ipa_general_american: 'ɪmˈbærəst',
      ipa_received_pronunciation: 'ɪmˈbærəst',
      cefr_level: 'B1',
      is_false_friend: 1,
      false_friend_note: '¡Falso amigo crítico! No significa "embarazada" (eso es "pregnant").',
      morphological_family_json: JSON.stringify(['embarrass', 'embarrassing', 'embarrassment']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b1_06',
      word: 'pretend',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'VERB',
      subcategory: 'Behavior Verb',
      definition_en: 'Speak and act so as to make it appear that something is the case when in fact it is not.',
      translation_es: 'Fingir / Simular',
      ipa_general_american: 'prɪˈtɛnd',
      ipa_received_pronunciation: 'prɪˈtɛnd',
      cefr_level: 'B1',
      is_false_friend: 1,
      false_friend_note: 'No significa "pretender" tener intenciones (eso es "to intend" o "to aim").',
      morphological_family_json: JSON.stringify(['pretense', 'pretender']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b1_07',
      word: 'intend',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'VERB',
      subcategory: 'Volition Verb',
      definition_en: 'Have in mind as a purpose or plan; plan to do something.',
      translation_es: 'Tener la intención de / Pretender',
      ipa_general_american: 'ɪnˈtɛnd',
      ipa_received_pronunciation: 'ɪnˈtɛnd',
      cefr_level: 'B1',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['intention', 'intentional', 'unintended']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b1_08',
      word: 'argue',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'VERB',
      subcategory: 'Communication Verb',
      definition_en: 'Give reasons or cite evidence in support of an idea, or dispute heatedly.',
      translation_es: 'Discutir / Pelear verbalmente / Argumentar',
      ipa_general_american: 'ˈɑːrɡjuː',
      ipa_received_pronunciation: 'ˈɑːɡjuː',
      cefr_level: 'B1',
      is_false_friend: 1,
      false_friend_note: 'Discutir pacíficamente un tema se dice "to discuss" o "to debate", no "to argue".',
      morphological_family_json: JSON.stringify(['argument', 'arguable', 'argumentative']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b1_09',
      word: 'discuss',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'VERB',
      subcategory: 'Communication Verb',
      definition_en: 'Talk about something with another person or group of people.',
      translation_es: 'Conversar / Debatir calmadamente sobre un tema',
      ipa_general_american: 'dɪˈskʌs',
      ipa_received_pronunciation: 'dɪˈskʌs',
      cefr_level: 'B1',
      is_false_friend: 1,
      false_friend_note: 'No implica conflicto; "discutir peleando" es "to argue". Además, nunca lleva "about" (*discuss about).',
      morphological_family_json: JSON.stringify(['discussion']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b1_10',
      word: 'cope',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'VERB',
      subcategory: 'Action Verb',
      definition_en: 'Deal effectively with something difficult.',
      translation_es: 'Lidiar con / Sobrellevar (seguido de "with")',
      ipa_general_american: 'koʊp',
      ipa_received_pronunciation: 'kəʊp',
      cefr_level: 'B1',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify([]),
      created_at: '2026-09-29T10:00:00Z',
    },

    // B2 (Upper Intermediate - Nuances, Precision & Collocations)
    {
      id: 'voc_b2_01',
      word: 'eventual',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Temporal Adjective',
      definition_en: 'Occurring at the end of a process; final or ultimate.',
      translation_es: 'Final / Definitivo',
      ipa_general_american: 'ɪˈvɛntʃuəl',
      ipa_received_pronunciation: 'ɪˈvɛntʃuəl',
      cefr_level: 'B2',
      is_false_friend: 1,
      false_friend_note: 'No significa "eventual" (casual u ocasional = occasional / sporadic).',
      morphological_family_json: JSON.stringify(['eventually', 'eventuality']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b2_02',
      word: 'eventually',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADVERB',
      subcategory: 'Temporal Adverb',
      definition_en: 'In the end, especially after a long delay, dispute, or series of problems.',
      translation_es: 'Al final / Con el tiempo / A la larga',
      ipa_general_american: 'ɪˈvɛntʃuəli',
      ipa_received_pronunciation: 'ɪˈvɛntʃuəli',
      cefr_level: 'B2',
      is_false_friend: 1,
      false_friend_note: 'No significa "eventualmente" (ocasionalmente = occasionally).',
      morphological_family_json: JSON.stringify(['eventual']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b2_03',
      word: 'comprehensive',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Descriptive Adjective',
      definition_en: 'Complete; including all or nearly all elements or aspects of something.',
      translation_es: 'Integral / Exhaustivo / Completo',
      ipa_general_american: 'ˌkɑːmprɪˈhɛnsɪv',
      ipa_received_pronunciation: 'ˌkɒmprɪˈhɛnsɪv',
      cefr_level: 'B2',
      is_false_friend: 1,
      false_friend_note: 'No significa "comprensivo" que entiende a otros (eso es "understanding" o "sympathetic").',
      morphological_family_json: JSON.stringify(['comprehend', 'comprehensively']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b2_04',
      word: 'sympathetic',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Personality Trait',
      definition_en: 'Feeling, showing, or expressing sympathy and compassion.',
      translation_es: 'Compasivo / Empático / Solidario',
      ipa_general_american: 'ˌsɪmpəˈθɛtɪk',
      ipa_received_pronunciation: 'ˌsɪmpəˈθɛtɪk',
      cefr_level: 'B2',
      is_false_friend: 1,
      false_friend_note: 'No significa "simpático" (agradable = friendly / nice / likable).',
      morphological_family_json: JSON.stringify(['sympathy', 'sympathize']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b2_05',
      word: 'consequence',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'NOUN',
      subcategory: 'Abstract Noun',
      definition_en: 'A result or effect of an action or condition.',
      translation_es: 'Consecuencia / Resultado',
      ipa_general_american: 'ˈkɑːnsəkwɛns',
      ipa_received_pronunciation: 'ˈkɒnsɪkwəns',
      cefr_level: 'B2',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['consequent', 'consequently']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b2_06',
      word: 'thorough',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Descriptive Adjective',
      definition_en: 'Complete with regard to every detail; not superficial or partial.',
      translation_es: 'Minucioso / Riguroso / A fondo',
      ipa_general_american: 'ˈθɜːroʊ',
      ipa_received_pronunciation: 'ˈθʌrə',
      cefr_level: 'B2',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['thoroughly', 'thoroughness']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b2_07',
      word: 'reluctant',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Attitude Adjective',
      definition_en: 'Unwilling and hesitant; disinclined.',
      translation_es: 'Renuente / Reacio',
      ipa_general_american: 'rɪˈlʌktənt',
      ipa_received_pronunciation: 'rɪˈlʌktənt',
      cefr_level: 'B2',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['reluctance', 'reluctantly']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b2_08',
      word: 'feasible',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Descriptive Adjective',
      definition_en: 'Possible to do easily or conveniently; workable.',
      translation_es: 'Factible / Viable',
      ipa_general_american: 'ˈfizəbəl',
      ipa_received_pronunciation: 'ˈfiːzɪbl',
      cefr_level: 'B2',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['feasibility']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b2_09',
      word: 'leverage',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'VERB',
      subcategory: 'Action Verb',
      definition_en: 'Use something to maximum advantage.',
      translation_es: 'Aprovechar al máximo / Potenciar',
      ipa_general_american: 'ˈlɛvərɪdʒ',
      ipa_received_pronunciation: 'ˈliːvərɪdʒ',
      cefr_level: 'B2',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify([]),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_b2_10',
      word: 'subtle',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Descriptive Adjective',
      definition_en: 'So delicate or precise as to be difficult to analyze or describe.',
      translation_es: 'Sutil (la "b" es muda)',
      ipa_general_american: 'ˈsʌtəl',
      ipa_received_pronunciation: 'ˈsʌtl',
      cefr_level: 'B2',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['subtlety', 'subtly']),
      created_at: '2026-09-29T10:00:00Z',
    },

    // C1 - C2 (Advanced Editorial & Academic Precision)
    {
      id: 'voc_c1_01',
      word: 'ubiquitous',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Descriptive Adjective',
      definition_en: 'Present, appearing, or found everywhere.',
      translation_es: 'Omnipresente / Ubicuo',
      ipa_general_american: 'juːˈbɪkwɪtəs',
      ipa_received_pronunciation: 'juːˈbɪkwɪtəs',
      cefr_level: 'C1',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['ubiquity']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_c1_02',
      word: 'scrutinize',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'VERB',
      subcategory: 'Cognitive Verb',
      definition_en: 'Examine or inspect closely and thoroughly.',
      translation_es: 'Examinar minuciosamente / Escrutar',
      ipa_general_american: 'ˈskruːtəˌnaɪz',
      ipa_received_pronunciation: 'ˈskruːtɪnaɪz',
      cefr_level: 'C1',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['scrutiny', 'inscrutable']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_c1_03',
      word: 'meticulous',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Personality Trait',
      definition_en: 'Showing great attention to detail; very careful and precise.',
      translation_es: 'Meticuloso / Concienzudo',
      ipa_general_american: 'məˈtɪkjələs',
      ipa_received_pronunciation: 'mɪˈtɪkjələs',
      cefr_level: 'C1',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['meticulously']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_c1_04',
      word: 'quintessential',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Descriptive Adjective',
      definition_en: 'Representing the most perfect or typical example of a quality or class.',
      translation_es: 'Por antonomasia / La quintaesencia de',
      ipa_general_american: 'ˌkwɪntəˈsɛnʃəl',
      ipa_received_pronunciation: 'ˌkwɪntɪˈsɛnʃl',
      cefr_level: 'C1',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['quintessence']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_c1_05',
      word: 'equivocal',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Descriptive Adjective',
      definition_en: 'Open to more than one interpretation; ambiguous or uncertain.',
      translation_es: 'Ambiguo / Dudoso / Equívoco',
      ipa_general_american: 'ɪˈkwɪvəkəl',
      ipa_received_pronunciation: 'ɪˈkwɪvəkl',
      cefr_level: 'C1',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['unequivocal', 'equivocate']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_c2_01',
      word: 'ephemeral',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Temporal Adjective',
      definition_en: 'Lasting for a very short time.',
      translation_es: 'Efímero / Fugaz',
      ipa_general_american: 'ɪˈfɛmərəl',
      ipa_received_pronunciation: 'ɪˈfɛmərəl',
      cefr_level: 'C2',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify([]),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_c2_02',
      word: 'surreptitious',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Behavior Adjective',
      definition_en: 'Kept secret, especially because it would not be approved of.',
      translation_es: 'Subrepticio / A hurtadillas / Furtivo',
      ipa_general_american: 'ˌsɜːrəpˈtɪʃəs',
      ipa_received_pronunciation: 'ˌsʌrəpˈtɪʃəs',
      cefr_level: 'C2',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['surreptitiously']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_c2_03',
      word: 'cacophony',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'NOUN',
      subcategory: 'Acoustic Noun',
      definition_en: 'A harsh, discordant mixture of sounds.',
      translation_es: 'Cacofonía / Estruendo discordante',
      ipa_general_american: 'kəˈkɑːfəni',
      ipa_received_pronunciation: 'kəˈkɒfəni',
      cefr_level: 'C2',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['cacophonous']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_c2_04',
      word: 'perfunctory',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Behavior Adjective',
      definition_en: 'Carried out with a minimum of effort or reflection.',
      translation_es: 'Superficial / Hecho por puro trámite',
      ipa_general_american: 'pərˈfʌŋktəri',
      ipa_received_pronunciation: 'pəˈfʌŋktəri',
      cefr_level: 'C2',
      is_false_friend: 0,
      false_friend_note: null,
      morphological_family_json: JSON.stringify(['perfunctorily']),
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'voc_c2_05',
      word: 'fastidious',
      grammatical_dimension: 'CONTENT',
      part_of_speech: 'ADJECTIVE',
      subcategory: 'Personality Trait',
      definition_en: 'Very attentive to and concerned about accuracy and detail.',
      translation_es: 'Exigente / Meticuloso en extremo',
      ipa_general_american: 'fæˈstɪdiəs',
      ipa_received_pronunciation: 'fæˈstɪdiəs',
      cefr_level: 'C2',
      is_false_friend: 1,
      false_friend_note: 'No significa "fastidioso" (molesto = annoying / bothersome).',
      morphological_family_json: JSON.stringify(['fastidiousness']),
      created_at: '2026-09-29T10:00:00Z',
    },
  ],

  phraseUnits: [
    {
      id: 'phr_01',
      primary_vocab_id: 'voc_b1_01',
      chunk_type: 'COLLOCATION',
      text: 'depend on',
      meaning_es: 'Depender de',
      phrasal_verb_type: null,
      example_1: 'Our schedule depends on the weather.',
      example_2: 'You cannot depend on him arriving on time.',
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'phr_02',
      primary_vocab_id: 'voc_b1_02',
      chunk_type: 'COLLOCATION',
      text: 'rely on',
      meaning_es: 'Confiar en / Depender de',
      phrasal_verb_type: null,
      example_1: 'We rely on customer feedback to improve.',
      example_2: 'Can I rely on you for help?',
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'phr_03',
      primary_vocab_id: null,
      chunk_type: 'COLLOCATION',
      text: 'make a decision',
      meaning_es: 'Tomar una decisión',
      phrasal_verb_type: null,
      example_1: 'It is time to make a decision.',
      example_2: 'We made a decision after consulting the team.',
      cefr_level: 'A2',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'phr_04',
      primary_vocab_id: null,
      chunk_type: 'COLLOCATION',
      text: 'pay attention',
      meaning_es: 'Prestar atención',
      phrasal_verb_type: null,
      example_1: 'Please pay attention to the instructions.',
      example_2: 'He was not paying attention during the meeting.',
      cefr_level: 'A2',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'phr_05',
      primary_vocab_id: null,
      chunk_type: 'PHRASAL_VERB',
      text: 'figure out',
      meaning_es: 'Descifrar / Encontrar la solución',
      phrasal_verb_type: 'TYPE_2_SEPARABLE',
      example_1: 'We need to figure out this problem.',
      example_2: 'I figured it out quickly.',
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'phr_06',
      primary_vocab_id: null,
      chunk_type: 'PHRASAL_VERB',
      text: 'carry out',
      meaning_es: 'Llevar a cabo / Realizar',
      phrasal_verb_type: 'TYPE_2_SEPARABLE',
      example_1: 'They carried out the inspection without issues.',
      example_2: 'The team will carry out the plan.',
      cefr_level: 'B2',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'phr_07',
      primary_vocab_id: null,
      chunk_type: 'PHRASAL_VERB',
      text: 'look forward to',
      meaning_es: 'Esperar con ansias (seguido de gerundio -ing o sustantivo)',
      phrasal_verb_type: 'TYPE_4_THREE_PART',
      example_1: 'I look forward to hearing from you.',
      example_2: 'We look forward to the weekend.',
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'phr_08',
      primary_vocab_id: null,
      chunk_type: 'COLLOCATION',
      text: 'take advantage of',
      meaning_es: 'Aprovechar (una oportunidad) / Sacar provecho de',
      phrasal_verb_type: null,
      example_1: 'You should take advantage of this opportunity.',
      example_2: 'He took advantage of the sunny day to run.',
      cefr_level: 'B2',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'phr_09',
      primary_vocab_id: null,
      chunk_type: 'IDIOM',
      text: 'keep in mind',
      meaning_es: 'Tener en cuenta / Recordar',
      phrasal_verb_type: null,
      example_1: 'Keep in mind that prices may change.',
      example_2: 'Please keep that in mind when planning.',
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'phr_10',
      primary_vocab_id: 'voc_b1_10',
      chunk_type: 'COLLOCATION',
      text: 'cope with',
      meaning_es: 'Lidiar con el estrés o dificultades',
      phrasal_verb_type: null,
      example_1: 'She learned how to cope with work pressure.',
      example_2: 'It is hard to cope with so many changes at once.',
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },
  ],

  contextExamples: [
    // Multiple rotating contexts for voc_b1_01 ('depend')
    {
      id: 'ctx_b1_01_a',
      vocab_id: 'voc_b1_01',
      phrase_id: 'phr_01',
      sentence_en: 'Whether we go camping will [depend on] the weather forecast.',
      sentence_es: 'Que vayamos a acampar dependerá del pronóstico del tiempo.',
      cloze_target: 'depend on',
      audio_url: null,
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'ctx_b1_01_b',
      vocab_id: 'voc_b1_01',
      phrase_id: 'phr_01',
      sentence_en: 'Small businesses often [depend on] word-of-mouth recommendations.',
      sentence_es: 'Los pequeños negocios frecuentemente dependen de recomendaciones boca a boca.',
      cloze_target: 'depend on',
      audio_url: null,
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'ctx_b1_01_c',
      vocab_id: 'voc_b1_01',
      phrase_id: 'phr_01',
      sentence_en: 'Children [depend on] their parents for guidance and emotional support.',
      sentence_es: 'Los niños dependen de sus padres para orientación y apoyo emocional.',
      cloze_target: 'depend on',
      audio_url: null,
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },

    // Rotating contexts for voc_a2_01 ('actually')
    {
      id: 'ctx_a2_01_a',
      vocab_id: 'voc_a2_01',
      phrase_id: null,
      sentence_en: 'I thought the test was tomorrow, but it is [actually] today.',
      sentence_es: 'Pensé que el examen era mañana, pero de hecho es hoy.',
      cloze_target: 'actually',
      audio_url: null,
      cefr_level: 'A2',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'ctx_a2_01_b',
      vocab_id: 'voc_a2_01',
      phrase_id: null,
      sentence_en: 'He looks young, but he is [actually] over forty years old.',
      sentence_es: 'Parece joven, pero en realidad tiene más de cuarenta años.',
      cloze_target: 'actually',
      audio_url: null,
      cefr_level: 'A2',
      created_at: '2026-09-29T10:00:00Z',
    },

    // Rotating contexts for voc_a2_02 ('currently')
    {
      id: 'ctx_a2_02_a',
      vocab_id: 'voc_a2_02',
      phrase_id: null,
      sentence_en: 'The software application is [currently] unavailable due to server maintenance.',
      sentence_es: 'La aplicación de software está actualmente no disponible por mantenimiento del servidor.',
      cloze_target: 'currently',
      audio_url: null,
      cefr_level: 'A2',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'ctx_a2_02_b',
      vocab_id: 'voc_a2_02',
      phrase_id: null,
      sentence_en: 'She is [currently] studying for her professional certification.',
      sentence_es: 'Actualmente ella está estudiando para su certificación profesional.',
      cloze_target: 'currently',
      audio_url: null,
      cefr_level: 'A2',
      created_at: '2026-09-29T10:00:00Z',
    },

    // Rotating contexts for voc_b1_03 ('sensible')
    {
      id: 'ctx_b1_03_a',
      vocab_id: 'voc_b1_03',
      phrase_id: null,
      sentence_en: 'Wearing warm boots in the snow was a very [sensible] choice.',
      sentence_es: 'Llevar botas abrigadas en la nieve fue una decisión muy sensata.',
      cloze_target: 'sensible',
      audio_url: null,
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'ctx_b1_03_b',
      vocab_id: 'voc_b1_03',
      phrase_id: null,
      sentence_en: 'She gave me some practical and [sensible] advice about money management.',
      sentence_es: 'Ella me dio un consejo práctico y sensato sobre administración de dinero.',
      cloze_target: 'sensible',
      audio_url: null,
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },

    // Rotating contexts for voc_b1_04 ('sensitive')
    {
      id: 'ctx_b1_04_a',
      vocab_id: 'voc_b1_04',
      phrase_id: null,
      sentence_en: 'My teeth are extremely [sensitive] to ice-cold beverages.',
      sentence_es: 'Mis dientes son extremadamente sensibles a las bebidas heladas.',
      cloze_target: 'sensitive',
      audio_url: null,
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'ctx_b1_04_b',
      vocab_id: 'voc_b1_04',
      phrase_id: null,
      sentence_en: 'Handle the confidential file carefully; it contains [sensitive] data.',
      sentence_es: 'Manipula el archivo confidencial con cuidado; contiene información delicada.',
      cloze_target: 'sensitive',
      audio_url: null,
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },

    // Rotating contexts for voc_b1_05 ('embarrassed')
    {
      id: 'ctx_b1_05_a',
      vocab_id: 'voc_b1_05',
      phrase_id: null,
      sentence_en: 'He felt deeply [embarrassed] when he forgot his colleague\'s name on stage.',
      sentence_es: 'Se sintió profundamente avergonzado cuando olvidó el nombre de su colega en el escenario.',
      cloze_target: 'embarrassed',
      audio_url: null,
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'ctx_b1_05_b',
      vocab_id: 'voc_b1_05',
      phrase_id: null,
      sentence_en: 'Do not be [embarrassed] to ask questions when you do not understand.',
      sentence_es: 'No te sientas apenado de hacer preguntas cuando no entiendas.',
      cloze_target: 'embarrassed',
      audio_url: null,
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },

    // Rotating contexts for voc_b2_09 ('leverage')
    {
      id: 'ctx_b2_09_a',
      vocab_id: 'voc_b2_09',
      phrase_id: null,
      sentence_en: 'Modern companies [leverage] cloud computing to reduce infrastructure costs.',
      sentence_es: 'Las empresas modernas aprovechan la computación en la nube para reducir costos de infraestructura.',
      cloze_target: 'leverage',
      audio_url: null,
      cefr_level: 'B2',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'ctx_b2_09_b',
      vocab_id: 'voc_b2_09',
      phrase_id: null,
      sentence_en: 'You can [leverage] your bilingual skills to unlock global career opportunities.',
      sentence_es: 'Puedes potenciar tus habilidades bilingües para desbloquear oportunidades laborales globales.',
      cloze_target: 'leverage',
      audio_url: null,
      cefr_level: 'B2',
      created_at: '2026-09-29T10:00:00Z',
    },
  ],

  phoneticRules: [
    {
      id: 'phon_01',
      rule_type: 'LINKING_CV',
      rule_name: 'Consonant-to-Vowel Linking',
      pattern_regex: '([b-df-hj-np-tv-z])\\s+([aeiou])',
      description_es: 'Cuando una palabra termina en consonante y la siguiente comienza por vocal, la consonante final salta a la sílaba inicial de la siguiente palabra.',
      example_sentence: 'Hold on an hour.',
      example_ipa_breakdown: '/hoʊl.dɒ.nə.naʊ.ər/',
      audio_sample_path: null,
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'phon_02',
      rule_type: 'LINKING_VV_J',
      rule_name: 'Intrusive /j/ Glide Linking',
      pattern_regex: '([iːɪeɪaɪɔɪ])\\s+([aeiou])',
      description_es: 'Tras vocales anteriores cerradas (/iː/, /ɪ/, /eɪ/, /aɪ/), se inserta un deslizamiento sonoro /j/ antes de la siguiente vocal.',
      example_sentence: 'I agree with the idea.',
      example_ipa_breakdown: '/aɪ.jəˈɡriː/',
      audio_sample_path: null,
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'phon_03',
      rule_type: 'LINKING_VV_W',
      rule_name: 'Intrusive /w/ Glide Linking',
      pattern_regex: '([uːʊoʊaʊ])\\s+([aeiou])',
      description_es: 'Tras vocales posteriores redondeadas (/uː/, /oʊ/, /aʊ/), se inserta un suave deslizamiento labiovelar /w/ antes de la siguiente vocal.',
      example_sentence: 'Go on, do it!',
      example_ipa_breakdown: '/ɡoʊ.wɒn . duː.wɪt/',
      audio_sample_path: null,
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'phon_04',
      rule_type: 'ELISION',
      rule_name: 'Alveolar Plosive Elision (/t/ & /d/)',
      pattern_regex: '([st|ft|nd|ld])\\s+([b-df-hj-np-tv-z])',
      description_es: 'Las oclusivas alveolares /t/ y /d/ desaparecen frecuentemente al estar intercaladas entre otras consonantes en habla fluida.',
      example_sentence: 'Next door to my best friend.',
      example_ipa_breakdown: '/nɛks.dɔːr . bɛs.frɛnd/',
      audio_sample_path: null,
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'phon_05',
      rule_type: 'ASSIMILATION_COALESCENT',
      rule_name: 'Coalescent Assimilation (Yod Coalescence)',
      pattern_regex: '([td])\\s+(y|you|your)',
      description_es: '/t/ + /j/ se fusiona en /tʃ/, y /d/ + /j/ se fusiona en /dʒ/.',
      example_sentence: 'Did you get what you needed?',
      example_ipa_breakdown: '/dɪ.dʒuː . wɒ.tʃuː/',
      audio_sample_path: null,
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'phon_06',
      rule_type: 'WEAK_FORM',
      rule_name: 'Preposition & Conjunction Weak Forms (/ə/)',
      pattern_regex: '\\b(to|for|at|from|can|and)\\b',
      description_es: 'En sílabas no acentuadas, las vocales plenas se reducen a la vocal neutra Schwa /ə/.',
      example_sentence: 'From time to time for lunch.',
      example_ipa_breakdown: '/frəm . tə . fə/',
      audio_sample_path: null,
      created_at: '2026-09-29T10:00:00Z',
    },
  ],

  grammarRules: [
    {
      id: 'gram_01',
      code: 'GRAM_STATIVE_VERBS',
      title: 'Stative Verbs in Continuous Tenses',
      category: 'VERB_TENSES',
      explanation_es: 'Los verbos que describen estados mentales, emociones o posesión (know, understand, believe, want, need) no se usan habitualmente en tiempos continuos con -ing.',
      formula_syntax: 'Subject + Verb [Present Simple] (NOT *Subject + is + Verb-ing)',
      contrastive_l1_note: 'En español se dice habitualmente "estoy entendiendo", pero en inglés lo natural es "I understand".',
      cefr_level: 'A2',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'gram_02',
      code: 'GRAM_DEPENDENT_PREP_ON',
      title: 'Dependent Preposition: Depend ON / Rely ON',
      category: 'PREPOSITIONS',
      explanation_es: 'Los verbos "depend" y "rely" siempre exigen la preposición "on", nunca "of".',
      formula_syntax: 'Subject + depend/rely + ON + Object',
      contrastive_l1_note: 'Interferencia directa del español "depender DE". Decir *"depend of" es un error fosilizado común.',
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },
    {
      id: 'gram_03',
      code: 'GRAM_COND_2',
      title: 'Second Conditional (Hypothetical Situations)',
      category: 'CLAUSES',
      explanation_es: 'Se utiliza para situaciones hipotéticas, improbables o imaginarias en el presente o futuro.',
      formula_syntax: 'If + Past Simple, ... would + bare infinitive',
      contrastive_l1_note: 'Equivale al pretérito imperfecto de subjuntivo + condicional simple en español (Si tuviera... compraría...).',
      cefr_level: 'B1',
      created_at: '2026-09-29T10:00:00Z',
    },
  ],

  errorTaxonomy: [
    {
      id: 'err_01',
      code: 'L1_PREP_DEPEND_ON',
      domain: 'GRAMMAR',
      severity: 'HIGH',
      label_es: 'Uso erróneo de "depend of" en lugar de "depend on"',
      detailed_explanation_es: 'Transferencia directa del español ("depender de"). En inglés siempre es "depend on" o "rely on".',
    },
    {
      id: 'err_02',
      code: 'LEX_FALSE_FRIEND_ACTUALLY',
      domain: 'LEXICON',
      severity: 'CRITICAL',
      label_es: 'Confusión de "actually" por "actualmente"',
      detailed_explanation_es: '"Actually" significa "en realidad/de hecho". Para decir "actualmente", use "currently" o "nowadays".',
    },
    {
      id: 'err_03',
      code: 'LEX_FALSE_FRIEND_SENSIBLE',
      domain: 'LEXICON',
      severity: 'MEDIUM',
      label_es: 'Confusión entre "sensible" y "sensitive"',
      detailed_explanation_es: '"Sensible" significa "sensato/prudente". Si quiere decir "sensible emocional o físicamente", use "sensitive".',
    },
    {
      id: 'err_04',
      code: 'PHON_CH_VS_SH',
      domain: 'PHONETICS',
      severity: 'MEDIUM',
      label_es: 'Contraste deficiente entre /tʃ/ (chair) y /ʃ/ (share)',
      detailed_explanation_es: 'Los hispanohablantes tienden a sustituir la fricativa postalveolar /ʃ/ por la africada /tʃ/.',
    },
  ],
};

/**
 * Seeds all master tables into the SQLite database.
 */
export async function seedDatabase(db: Kysely<DatabaseSchema>): Promise<void> {
  // 1. Vocab items
  for (const item of SEED_DATA.vocabItems) {
    await db
      .insertInto('vocab_items')
      .values(item)
      .onConflict((oc) => oc.column('id').doNothing())
      .execute();
  }

  // 2. Phrase units
  for (const phrase of SEED_DATA.phraseUnits) {
    await db
      .insertInto('phraseological_units')
      .values(phrase)
      .onConflict((oc) => oc.column('id').doNothing())
      .execute();
  }

  // 3. Context examples
  for (const ctx of SEED_DATA.contextExamples) {
    await db
      .insertInto('vocab_context_examples')
      .values(ctx)
      .onConflict((oc) => oc.column('id').doNothing())
      .execute();
  }

  // 4. Phonetic rules
  for (const rule of SEED_DATA.phoneticRules) {
    await db
      .insertInto('phonetic_rules')
      .values(rule)
      .onConflict((oc) => oc.column('id').doNothing())
      .execute();
  }

  // 5. Grammar rules
  for (const grammar of SEED_DATA.grammarRules) {
    await db
      .insertInto('grammar_rules')
      .values(grammar)
      .onConflict((oc) => oc.column('id').doNothing())
      .execute();
  }

  // 6. Error taxonomy
  for (const taxon of SEED_DATA.errorTaxonomy) {
    await db
      .insertInto('error_taxonomy')
      .values(taxon)
      .onConflict((oc) => oc.column('id').doNothing())
      .execute();
  }
}
